version: '3.2'

services:
  mysql:
    image: mysql:5.7
    restart: always
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - ./volumes/mysql/init:/docker-entrypoint-initdb.d:ro
      - ./volumes/mysql/data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    env_file: .env
    restart: always
    ports:
     - 8081:80

  rabbitmq:
    image: rabbitmq:3.7-management
    env_file: .env
    ports:
      - 15672:15672
      - 5672:5672

  dashboard:
    build:
      context: ./Dashboard/
      dockerfile: compose/Dockerfile
    ports:
      - 9000:9000
      

volumes:
  rabbitmq-data:
    driver: local
